apiVersion: v2
name: dummy-app2
description: A Helm chart for a dummy app used for testing
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: component-chart
    repository: https://charts.devspace.sh
    version: 0.9.0
    alias: app