---
name: Updatecli

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run once a day 
    - cron: '0 0 * * *'

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  updatecli:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Run Updatecli in apply mode
        env:
          GH_USERNAME: "${{ secrets.GH_USERNAME }}"
          GH_PASSWORD: "${{ secrets.GH_PASSWORD }}"
        run: "updatecli apply --config ./updatecli/updatecli.d"

      - name: GIT commit and push all changed files
        env:
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: gitops
          CI_COMMIT_EMAIL: gitops@myspotontheweb.com
        run: |
          git config --global user.name  "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "${{ env.CI_COMMIT_EMAIL }}"
          git commit -am "${{ env.CI_COMMIT_MESSAGE }}"
          git pull --rebase
          git push
