---
name: Updatecli

on:
  workflow_dispatch:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run once a day 
    - cron: '0 0 * * *'

permissions:
  contents: "write"
  pull-requests: "write"

jobs:
  updatecli:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Updatecli in the runner
        uses: updatecli/updatecli-action@v2

      - name: Run Updatecli in apply mode
        run: "updatecli apply --config ./updatecli/updatecli.d"
        env:
          GH_USERNAME: "${{ secrets.GH_USERNAME }}"
          GH_PASSWORD: "${{ secrets.GH_PASSWORD }}"

      - name: Commit changes
        run: |
          git config user.email "gitops@myspotontheweb.com"
          git config user.name "gitops"
          git commit -am "Gitops update by updatecli"
          git pull --rebase
          git push
